# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "CompuTruthing"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Blog about computing and truthing. About the search for the essence of computing. About understanding the essence of knowledge. And some other interesting stuff, technical and not that technical."

# Tagline near the site title
tagline: "thoughts on Computing and Truthing"

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://lucteo.ro"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: lucteo-github-io

# Google Analytics ID
google_analytics_id: "UA-110998351-1"

# Author information - author info at the bottom of the post
author_name: "LucTeo"
author_bio: "Lucian Radu Teodorescu holds a PhD in programming languages, and is a Software Architect at Garmin International.  He likes challenges; and understanding the essence of things (if there is one) constitutes the biggest challenge of all."
author_url:  "lucteo.github.io"
author_location: "Cluj-Napoca, Romania"
author_image: /images/authorimage.jpg

# Sidebar Add banner
# banner_url: "http://justgoodthemes.com"
# banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
# TODO: Do I need this?

# Social links in the site footer
github_username: "lucteo"
twitter_username: "@LucT3o"
# facebook_username: "username"
# googleplus_username: "+username"
# codepen_username: "username"
# dribbble_uername: "username"
# medium_username: "@username"
# instagram_username: "username"
# pinterest_username: "username"
linkedin_username: "lteodorescu"
# weibo_username: "username"

# SEO
twitter:
  username: LucT3o
social:
  name: Lucian Radu Teodorescu
  links:
    - https://twitter.com/@LucT3o
    - https://www.linkedin.com/in/lteodorescu
    - https://github.com/lucteo
logo: /images/authorimage.jpg


# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins:
    - jekyll-paginate
    - jemoji
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-minifier

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false

# Jekyll-minifier settings
jekyll-minifier:
  preserve_php: false               # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
